BEGIN TRANSACTION;
CREATE TABLE "gongxun"([level] int(11) NOT NULL,[name] varchar(20) NOT NULL,[score] int(11) NOT NULL,[category] varchar(10) NOT NULL, Primary Key(level,category) ON CONFLICT Ignore);
CREATE TABLE "skills"([skillname] varchar(20) NOT NULL,[gained] int(11) NOT NULL,[used] int(11) NOT NULL, Primary Key(skillname) ON CONFLICT Ignore);
CREATE TABLE "gamedata"([id] varchar(20) NOT NULL,[num] int(11) NOT NULL, Primary Key(id) ON CONFLICT Ignore);
CREATE TABLE "zhangong"([id] varchar(10) NOT NULL,[name] varchar(30) NOT NULL,[score] int(11) NOT NULL,[description] varchar(250) NOT NULL,[gained] int(11) NOT NULL,[category] varchar(20) NOT NULL,[lasttime] datetime NOT NULL,[general] varchar(40) NOT NULL,[num] int(11) NOT NULL,[count] int(11) NOT NULL, Primary Key(id) ON CONFLICT Ignore);
CREATE TABLE "results"([id] int(11) NOT NULL,[general] varchar(30) NOT NULL,[role] varchar(10) NOT NULL,[kingdom] varchar(10) NOT NULL,[hegemony] int(11) NOT NULL,[mode] varchar(10) NOT NULL,[turncount] int(11) NOT NULL,[alive] int(11) NOT NULL,[result] varchar(10) NOT NULL,[wen] int(11) NOT NULL,[wu] int(11) NOT NULL,[expval] int(11) NOT NULL,[zhangong] varchar(255) NOT NULL, Primary Key(id) ON CONFLICT Ignore);
CREATE INDEX [gamedata_num] On [gamedata] ([num] );
CREATE INDEX [results_result] On [results] ([result]);
CREATE INDEX [results_role] On [results] ([role]);
CREATE INDEX [results_general] On [results] ([general]);
CREATE INDEX [results_kingdom] On [results] ([kingdom]);
CREATE INDEX [results_hegemony] On [results] ([hegemony]);
CREATE INDEX [results_mode] On [results] ([mode]);
CREATE INDEX [gongxun_score] On [gongxun] ([score]);
CREATE INDEX [gongxun_category] On [gongxun] ([category]);
CREATE INDEX [zhangong_category] On [zhangong] ([category]);
CREATE INDEX [zhangong_general] On [zhangong] ([general]);
CREATE INDEX [zhangong_num] On [zhangong] ([num]);
CREATE INDEX [skills_gained] On [skills] ([gained]);
CREATE INDEX [skills_used] On [skills] ([used]);
INSERT INTO "gongxun" VALUES(0, '平民', 0, 'wen');
INSERT INTO "gongxun" VALUES(1, '里长', 100, 'wen');
INSERT INTO "gongxun" VALUES(2, '亭长', 300, 'wen');
INSERT INTO "gongxun" VALUES(3, '蔷夫', 600, 'wen');
INSERT INTO "gongxun" VALUES(4, '县尉', 1000, 'wen');
INSERT INTO "gongxun" VALUES(5, '郎中', 1500, 'wen');
INSERT INTO "gongxun" VALUES(6, '侍郎', 2100, 'wen');
INSERT INTO "gongxun" VALUES(7, '县丞', 2800, 'wen');
INSERT INTO "gongxun" VALUES(8, '县长', 3600, 'wen');
INSERT INTO "gongxun" VALUES(9, '博士', 4500, 'wen');
INSERT INTO "gongxun" VALUES(10, '议郎', 5500, 'wen');
INSERT INTO "gongxun" VALUES(11, '中郎', 6600, 'wen');
INSERT INTO "gongxun" VALUES(12, '谒者', 7800, 'wen');
INSERT INTO "gongxun" VALUES(13, '郡长史', 9100, 'wen');
INSERT INTO "gongxun" VALUES(14, '州刺史', 10500, 'wen');
INSERT INTO "gongxun" VALUES(15, '郡太守丞', 12000, 'wen');
INSERT INTO "gongxun" VALUES(16, '谏大夫', 13600, 'wen');
INSERT INTO "gongxun" VALUES(17, '太常丞', 15300, 'wen');
INSERT INTO "gongxun" VALUES(18, '光禄丞', 17100, 'wen');
INSERT INTO "gongxun" VALUES(19, '卫尉丞', 19000, 'wen');
INSERT INTO "gongxun" VALUES(20, '太仆丞', 21000, 'wen');
INSERT INTO "gongxun" VALUES(21, '大鸿胪丞', 23100, 'wen');
INSERT INTO "gongxun" VALUES(22, '宗正丞', 25300, 'wen');
INSERT INTO "gongxun" VALUES(23, '大司农丞', 27600, 'wen');
INSERT INTO "gongxun" VALUES(24, '少府丞', 30000, 'wen');
INSERT INTO "gongxun" VALUES(25, '太中大夫', 32500, 'wen');
INSERT INTO "gongxun" VALUES(26, '谒者仆射', 35100, 'wen');
INSERT INTO "gongxun" VALUES(27, '廷尉正监', 37800, 'wen');
INSERT INTO "gongxun" VALUES(28, '中常侍', 40600, 'wen');
INSERT INTO "gongxun" VALUES(29, '尚书令', 43500, 'wen');
INSERT INTO "gongxun" VALUES(30, '御史中丞', 46500, 'wen');
INSERT INTO "gongxun" VALUES(31, '司徒长史', 49600, 'wen');
INSERT INTO "gongxun" VALUES(32, '太尉长史', 52800, 'wen');
INSERT INTO "gongxun" VALUES(33, '司空长史', 56100, 'wen');
INSERT INTO "gongxun" VALUES(34, '丞相司直', 59500, 'wen');
INSERT INTO "gongxun" VALUES(35, '光禄大夫', 63000, 'wen');
INSERT INTO "gongxun" VALUES(36, '侍中', 66600, 'wen');
INSERT INTO "gongxun" VALUES(37, '州牧', 70300, 'wen');
INSERT INTO "gongxun" VALUES(38, '郡太守', 74100, 'wen');
INSERT INTO "gongxun" VALUES(39, '执金吾', 78000, 'wen');
INSERT INTO "gongxun" VALUES(40, '太常', 82000, 'wen');
INSERT INTO "gongxun" VALUES(41, '光禄勋', 86100, 'wen');
INSERT INTO "gongxun" VALUES(42, '卫尉', 90300, 'wen');
INSERT INTO "gongxun" VALUES(43, '太仆', 94600, 'wen');
INSERT INTO "gongxun" VALUES(44, '廷尉', 99000, 'wen');
INSERT INTO "gongxun" VALUES(45, '大鸿胪', 103500, 'wen');
INSERT INTO "gongxun" VALUES(46, '宗正', 108100, 'wen');
INSERT INTO "gongxun" VALUES(47, '司徒', 112800, 'wen');
INSERT INTO "gongxun" VALUES(48, '太尉', 117600, 'wen');
INSERT INTO "gongxun" VALUES(49, '司空', 122500, 'wen');
INSERT INTO "gongxun" VALUES(50, '丞相', 127500, 'wen');
INSERT INTO "gongxun" VALUES(0, '平民', 0, 'wu');
INSERT INTO "gongxun" VALUES(1, '兵卒', 100, 'wu');
INSERT INTO "gongxun" VALUES(2, '屯长', 300, 'wu');
INSERT INTO "gongxun" VALUES(3, '军侯', 600, 'wu');
INSERT INTO "gongxun" VALUES(4, '军司马', 1000, 'wu');
INSERT INTO "gongxun" VALUES(5, '都尉', 1500, 'wu');
INSERT INTO "gongxun" VALUES(6, '校尉', 2100, 'wu');
INSERT INTO "gongxun" VALUES(7, '中郎将', 2800, 'wu');
INSERT INTO "gongxun" VALUES(8, '裨将军', 3600, 'wu');
INSERT INTO "gongxun" VALUES(9, '偏将军', 4500, 'wu');
INSERT INTO "gongxun" VALUES(10, '牙门将军', 5500, 'wu');
INSERT INTO "gongxun" VALUES(11, '伏波将军', 6600, 'wu');
INSERT INTO "gongxun" VALUES(12, '翊武将军', 7800, 'wu');
INSERT INTO "gongxun" VALUES(13, '翊师将军', 9100, 'wu');
INSERT INTO "gongxun" VALUES(14, '建威将军', 10500, 'wu');
INSERT INTO "gongxun" VALUES(15, '建武将军', 12000, 'wu');
INSERT INTO "gongxun" VALUES(16, '振威将军', 13600, 'wu');
INSERT INTO "gongxun" VALUES(17, '振武将军', 15300, 'wu');
INSERT INTO "gongxun" VALUES(18, '领军将军', 17100, 'wu');
INSERT INTO "gongxun" VALUES(19, '护军将军', 19000, 'wu');
INSERT INTO "gongxun" VALUES(20, '武卫将军', 21000, 'wu');
INSERT INTO "gongxun" VALUES(21, '中垒将军', 23100, 'wu');
INSERT INTO "gongxun" VALUES(22, '镇军将军', 25300, 'wu');
INSERT INTO "gongxun" VALUES(23, '抚军将军', 27600, 'wu');
INSERT INTO "gongxun" VALUES(24, '镇国将军', 30000, 'wu');
INSERT INTO "gongxun" VALUES(25, '龙骧将军', 32500, 'wu');
INSERT INTO "gongxun" VALUES(26, '平东将军', 35100, 'wu');
INSERT INTO "gongxun" VALUES(27, '平南将军', 37800, 'wu');
INSERT INTO "gongxun" VALUES(28, '平西将军', 40600, 'wu');
INSERT INTO "gongxun" VALUES(29, '平北将军', 43500, 'wu');
INSERT INTO "gongxun" VALUES(30, '安东将军', 46500, 'wu');
INSERT INTO "gongxun" VALUES(31, '安南将军', 49600, 'wu');
INSERT INTO "gongxun" VALUES(32, '安西将军', 52800, 'wu');
INSERT INTO "gongxun" VALUES(33, '安北将军', 56100, 'wu');
INSERT INTO "gongxun" VALUES(34, '镇东将军', 59500, 'wu');
INSERT INTO "gongxun" VALUES(35, '镇南将军', 63000, 'wu');
INSERT INTO "gongxun" VALUES(36, '镇西将军', 66600, 'wu');
INSERT INTO "gongxun" VALUES(37, '镇北将军', 70300, 'wu');
INSERT INTO "gongxun" VALUES(38, '征东将军', 74100, 'wu');
INSERT INTO "gongxun" VALUES(39, '征南将军', 78000, 'wu');
INSERT INTO "gongxun" VALUES(40, '征西将军', 82000, 'wu');
INSERT INTO "gongxun" VALUES(41, '征北将军', 86100, 'wu');
INSERT INTO "gongxun" VALUES(42, '前将军', 90300, 'wu');
INSERT INTO "gongxun" VALUES(43, '后将军', 94600, 'wu');
INSERT INTO "gongxun" VALUES(44, '左将军', 99000, 'wu');
INSERT INTO "gongxun" VALUES(45, '右将军', 103500, 'wu');
INSERT INTO "gongxun" VALUES(46, '骠骑将军', 108100, 'wu');
INSERT INTO "gongxun" VALUES(47, '车骑将军', 112800, 'wu');
INSERT INTO "gongxun" VALUES(48, '卫将军', 117600, 'wu');
INSERT INTO "gongxun" VALUES(49, '安国将军', 122500, 'wu');
INSERT INTO "gongxun" VALUES(50, '大将军', 127500, 'wu');
INSERT INTO "skills" VALUES('zhiyu', 0, 0);
INSERT INTO "skills" VALUES('miji', 0, 0);
INSERT INTO "skills" VALUES('anxu', 0, 0);
INSERT INTO "skills" VALUES('jiangchi', 0, 0);
INSERT INTO "skills" VALUES('zishou', 0, 0);
INSERT INTO "skills" VALUES('zongshi', 0, 0);
INSERT INTO "skills" VALUES('lihuo', 0, 0);
INSERT INTO "skills" VALUES('mashu', 0, 0);
INSERT INTO "skills" VALUES('kuanggu', 0, 0);
INSERT INTO "skills" VALUES('liegong', 0, 0);
INSERT INTO "skills" VALUES('shensu', 0, 0);
INSERT INTO "skills" VALUES('hongyuan', 0, 0);
INSERT INTO "skills" VALUES('mingzhe', 0, 0);
INSERT INTO "skills" VALUES('wansha', 0, 0);
INSERT INTO "skills" VALUES('yinghun', 0, 0);
INSERT INTO "skills" VALUES('weimu', 0, 0);
INSERT INTO "skills" VALUES('roulin', 0, 0);
INSERT INTO "skills" VALUES('zaiqi', 0, 0);
INSERT INTO "skills" VALUES('haoshi', 0, 0);
INSERT INTO "skills" VALUES('dimeng', 0, 0);
INSERT INTO "skills" VALUES('xingshang', 0, 0);
INSERT INTO "skills" VALUES('fangzhu', 0, 0);
INSERT INTO "skills" VALUES('duanliang', 0, 0);
INSERT INTO "skills" VALUES('lieren', 0, 0);
INSERT INTO "skills" VALUES('longdan', 0, 0);
INSERT INTO "skills" VALUES('qicai', 0, 0);
INSERT INTO "skills" VALUES('tieji', 0, 0);
INSERT INTO "skills" VALUES('wushuang', 0, 0);
INSERT INTO "skills" VALUES('tiandu', 0, 0);
INSERT INTO "skills" VALUES('guose', 0, 0);
INSERT INTO "skills" VALUES('zhiheng', 0, 0);
INSERT INTO "skills" VALUES('lijian', 0, 0);
INSERT INTO "skills" VALUES('biyue', 0, 0);
INSERT INTO "skills" VALUES('ganglie', 0, 0);
INSERT INTO "skills" VALUES('qianxun', 0, 0);
INSERT INTO "skills" VALUES('wusheng', 0, 0);
INSERT INTO "skills" VALUES('qingguo', 0, 0);
INSERT INTO "skills" VALUES('fankui', 0, 0);
INSERT INTO "skills" VALUES('jianxiong', 0, 0);
INSERT INTO "skills" VALUES('guanxing', 0, 0);
INSERT INTO "skills" VALUES('tuxi', 0, 0);
INSERT INTO "skills" VALUES('yingzi', 0, 0);
INSERT INTO "skills" VALUES('fanjian', 0, 0);
INSERT INTO "skills" VALUES('dahe', 0, 0);
INSERT INTO "skills" VALUES('yanzheng', 0, 0);
INSERT INTO "skills" VALUES('tanhu', 0, 0);
INSERT INTO "skills" VALUES('yanxiao', 0, 0);
INSERT INTO "skills" VALUES('anxian', 0, 0);
INSERT INTO "skills" VALUES('jilei', 0, 0);
INSERT INTO "skills" VALUES('danlao', 0, 0);
INSERT INTO "skills" VALUES('weidi', 0, 0);
INSERT INTO "skills" VALUES('yicong', 0, 0);
INSERT INTO "skills" VALUES('mengjin', 0, 0);
INSERT INTO "skills" VALUES('xiuluo', 0, 0);
INSERT INTO "skills" VALUES('shenwei', 0, 0);
INSERT INTO "skills" VALUES('shenji', 0, 0);
INSERT INTO "skills" VALUES('zhulou', 0, 0);
INSERT INTO "skills" VALUES('tannang', 0, 0);
INSERT INTO "skills" VALUES('neofanjian', 0, 0);
INSERT INTO "skills" VALUES('yishi', 0, 0);
INSERT INTO "skills" VALUES('enyuan', 0, 0);
INSERT INTO "skills" VALUES('xuanhuo', 0, 0);
INSERT INTO "skills" VALUES('xianzhen', 0, 0);
INSERT INTO "skills" VALUES('xuanfeng', 0, 0);
INSERT INTO "skills" VALUES('yizhong', 0, 0);
INSERT INTO "skills" VALUES('shangshi', 0, 0);
INSERT INTO "skills" VALUES('ganlu', 0, 0);
INSERT INTO "skills" VALUES('luoying', 0, 0);
INSERT INTO "skills" VALUES('jujian', 0, 0);
INSERT INTO "skills" VALUES('xinzhan', 0, 0);
INSERT INTO "skills" VALUES('zhichi', 0, 0);
INSERT INTO "skills" VALUES('mingce', 0, 0);
INSERT INTO "skills" VALUES('pojun', 0, 0);
INSERT INTO "skills" VALUES('qiangxi', 0, 0);
INSERT INTO "skills" VALUES('lianhuan', 0, 0);
INSERT INTO "skills" VALUES('tianyi', 0, 0);
INSERT INTO "skills" VALUES('bazhen', 0, 0);
INSERT INTO "skills" VALUES('quhu', 0, 0);
INSERT INTO "skills" VALUES('luanji', 0, 0);
INSERT INTO "skills" VALUES('feiying', 0, 0);
INSERT INTO "skills" VALUES('qinyin', 0, 0);
INSERT INTO "skills" VALUES('juejing', 0, 0);
INSERT INTO "skills" VALUES('shelie', 0, 0);
INSERT INTO "skills" VALUES('gongxin', 0, 0);
INSERT INTO "skills" VALUES('jiang', 0, 0);
INSERT INTO "skills" VALUES('guzheng', 0, 0);
INSERT INTO "skills" VALUES('zhijian', 0, 0);
INSERT INTO "skills" VALUES('tiaoxin', 0, 0);
INSERT INTO "skills" VALUES('xiangle', 0, 0);
INSERT INTO "skills" VALUES('fangquan', 0, 0);
INSERT INTO "skills" VALUES('nosenyuan', 0, 0);
INSERT INTO "skills" VALUES('jueqing', 0, 0);
INSERT INTO "skills" VALUES('yiji', 0, 0);
INSERT INTO "skills" VALUES('liuli', 0, 0);
INSERT INTO "skills" VALUES('neoganglie', 0, 0);
INSERT INTO "skills" VALUES('beige', 0, 0);
INSERT INTO "skills" VALUES('zhiji', 0, 0);
INSERT INTO "skills" VALUES('zhiba', 0, 0);
INSERT INTO "skills" VALUES('nosxuanhuo', 0, 0);
INSERT INTO "skills" VALUES('juxiang', 0, 0);
INSERT INTO "gamedata" VALUES('bszj', 0);
INSERT INTO "gamedata" VALUES('yqt', 0);
INSERT INTO "gamedata" VALUES('gddph', 0);
INSERT INTO "gamedata" VALUES('ph', 0);
COMMIT;